doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            user_user_role: 'App\Model\User\Entity\UserRoleType'
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Post:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Post/Entity'
                prefix: 'App\Model\Post\Entity'
                alias: Post