security:
    providers:
        fetcher:
            id: App\Security\UserProvider
    encoders:
        App\Security\UserIdentity: native
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                entry_point: App\Security\LoginFormAuthenticator

            form_login: true
            logout:
                path:   app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/posts/create, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/posts/view, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/posts, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }